### ISSUE TITLE
Error if result is not an instanceof ExecutedStepResult

### ISSUE THREAD

**Issue by GROwen** [integratedexperts/behat-format-progress-fail#7]
On https://github.com/integratedexperts/behat-format-progress-fail/blob/master/src/IntegratedExperts/BehatFormatProgressFail/Printer/PrinterProgressFail.php#L94 `getCallResult` only exists on the `ExecutedStepResult` class so if the result is instead an instance of `FailedStepSearchResult` (for example if a step definition returns an ambiguous result) the formatter throws an unrecoverable error.

**Comment by AlexSkrypnyk** [comment]
implemented in #11
